CREATE TABLE IF NOT EXISTS "REFERENCE_DATA"(
    "REFERENCE_DATA_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "REFERENCE_DATA_QUERY" VARCHAR2(2000 BYTE) NOT NULL ENABLE
   );
ALTER TABLE "REFERENCE_DATA" ADD CONSTRAINT "REFERENCE_DATA_PK" PRIMARY KEY ("REFERENCE_DATA_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ENABLE;

DELETE FROM "REFERENCE_DATA";
COMMIT;

INSERT INTO "REFERENCE_DATA" (REFERENCE_DATA_CODE, REFERENCE_DATA_QUERY)
VALUES ('project-types',
'SELECT
  TS_PROJECT_TYPE_CODE "code",
  TS_PROJECT_TYPE_DESC "description"
FROM TS_PROJECT_TYPE_CODES'
);

INSERT INTO "REFERENCE_DATA" (REFERENCE_DATA_CODE, REFERENCE_DATA_QUERY)
VALUES ('project-type-offices',
'SELECT
  o.OFFICE_CODE "officeCode",
  o.OFFICE_NAME "officeName"
FROM TS_PROJECT_TYPE_OFFICES pto
JOIN OFFICES o ON pto.OFFICE_SEQ_ID = o.OFFICE_SEQ_ID
WHERE pto.TS_PROJECT_TYPE_CODE = ''Approval'' 
AND o.OFFICE_TYPE_CODE = ''Division''
AND pto.ACTIVE_IND = ''Y''
ORDER BY o.office_code'
);

COMMIT;
